server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/on_trust?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
       ddl-auto: validate
  data:
    web:
      pageable:
        one-indexed-parameters: true
  devtools:
    # Auto Restart
    restart:
      enabled: true
      additional-exclude: static/**,public/**
    livereload:
      enabled: true