server:
  port: 8000

spring:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
       ddl-auto: update
    open-in-view: false
    properties:
       hibernate:
         show_sql: true
         format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    url: jdbc:mysql://localhost:3306/on_trust?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    # Auto Restart
    restart:
      enabled: true
      additional-exclude: static/**,public/**
    livereload:
      enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: WARN